image: alpine/edge
packages:
  - cmake
  - ninja
  - liburing-dev
  - linux-headers
  - gtest-dev
sources:
  - https://github.com/3541/short-circuit
tasks:
  - submodules: |
      cd short-circuit
      git submodule update --init --recursive
  - setup: |
      mkdir -p short-circuit/build
      cmake -GNinja -S short-circuit -B short-circuit/build -DCMAKE_BUILD_TYPE=Release -DUSE_WERROR=1
  - build: |
      cmake --build short-circuit/build
  - test: |
      cmake --build short-circuit/build --target test
