version: 2.1

jobs:
  build-aarch64:
    parameters:
      backend:
        description: "IO backend"
        default: "uring"
        type: string
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - run: |
          pip3 install meson
          sudo apt-get update
          sudo apt-get install ninja-build gcc-10 g++-10
          if [ "<<parameters.backend>>" = "uring" ]; then
              LIBURING=$(mktemp -d)
              git clone https://github.com/axboe/liburing $LIBURING
              cd $LIBURING
              git checkout liburing-2.1
              ./configure
              make -C src -j$(nproc)
              sudo make install
          fi
      - checkout
      - run:
          name: "Configure"
          command: "ci/configure.sh build -Dio_backend=<<parameters.backend>>"
      - run:
          name: "Build"
          command: "ci/build.sh build"
      - run:
          name: "Test"
          command: "ci/test.sh build"
      - store_test_results:
          path: build/sc_gtest.xml
workflows:
  build-and-test:
    jobs:
      - build-aarch64:
          name: build-aarch64-uring
          backend: uring
      - build-aarch64:
          name: build-aarch64-poll
          backend: poll
