version: 2.1

jobs:
  build-aarch64:
    parameters:
      backend:
        description: "IO backend"
        default: "uring"
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: |
          pip3 install meson
          sudo apt-get update
          sudo apt-get install ninja-build gcc-10 g++-10 valgrind
          if [ "<<parameters.backend>>" = "uring" ]; then
              LIBURING=$(mktemp -d)
              git clone https://github.com/axboe/liburing $LIBURING
              cd $LIBURING
              ./configure
              make -C src -j$(nproc)
              sudo make install
          fi
      - checkout
      - run:
          name: "Configure"
          command: "CC=gcc-10 CXX=g++-10 meson setup --buildtype debug --werror -Dio_backend=<<parameters.backend>> -Db_sanitize=address,undefined -Dci=true build"
      - run:
          name: "Build"
          command: "meson compile -C build"
      - run:
          name: "Test"
          command: "meson test -C build"
      - store_test_results:
          path: build/sc_gtest.xml
workflows:
  build-and-test:
    jobs:
      - build-aarch64:
          name: build-aarch64-uring
          backend: uring
      - build-aarch64:
          name: build-aarch64-poll
          backend: poll
