#!/bin/sh
set -e

BASE=$(dirname $(readlink -f "$0"))

rm -rf build

meson build/debug --buildtype=debug -Db_coverage=true $@
if command -v clang &> /dev/null; then
   meson build/debug_clang --native-file="$BASE/meson/clang.ini" --buildtype=debug -Db_coverage=true $@
   meson build/release_clang --native-file="$BASE/meson/clang.ini" --buildtype=release -Db_lto=true $@
fi
meson build/san --buildtype=debug -Db_sanitize=address,undefined $@
meson build/debugopt --buildtype=debugoptimized -Db_lto=true $@
meson build/profile --buildtype=debugoptimized -Db_ndebug=true -Dprofile=true $@
meson build/release --buildtype=release -Db_lto=true $@
