name: Build and test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.c'
      - '**/*.h'
      - '**/*.cc'
      - '**/*.hh'
      - '.github/workflows/build.yml'
      - '**/meson.build'
      - 'subprojects/a3.wrap'
      - 'boilerplate'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: actions/checkout@v4
      with:
        repository: axboe/liburing
        path: liburing

    - name: Build and install liburing
      run: |
        cd ${{runner.workspace}}/short-circuit/liburing
        ./configure
        make
        sudo make install

    - name: Install dependencies
      run: pip install meson ninja

    - name: Configure
      run: meson setup --buildtype debug --werror -Db_sanitize=address,undefined build

    - name: Build
      run: meson compile -C build

    - name: Test
      run: meson test -C build
