name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt-get -y install meson ninja
      - name: configure
        run: ./configure
      - name: build-debug
        run: meson build -C build/debug
      - name: build-release
        run: meson build -C build/release
